variable "security_groups" {}
variable "vpc_id" {}
variable "lb_healthy_threshold" {}
variable "lb_unhealthy_threshold" {}
variable "lb_timeout" {}
variable "lb_interval" {}
variable "public_subnets" {}
variable "private_sg" {}
variable "app_tier_sg" {}
variable "app_tier_sn" {}